apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-idp
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: RyanJKS/backstage-idp
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: ryanjks@gmail.com
  lifecycle: experimental
