global:
  postgresql:
    auth:
      username: backstage
      database: backstage
      existingSecret: backstage-secrets
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
        userPasswordKey: POSTGRES_PASSWORD
primary:
  name: primary
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  persistence:
    enabled: true
    size: 8Gi
